"""Package containing modularized liara-memory backing store implementations."""

from __future__ import annotations

from services.memory.stores.backed import BackedMemoryServiceStore
from services.memory.stores.base import (
    EphemeralMemoryStore,
    MemoryServiceStore,
    NullMemoryStore,
    _append_embedding_request_audit,
    _build_session_summary_candidate,
    _compact_summary_text,
    _context_contains_sensitive_data,
    _context_scope_present,
    _embedding_text_fingerprint,
    _estimate_token_count,
    _is_truthy,
    _parse_aware_datetime,
)
from services.memory.stores.factory import create_default_memory_service_store
from services.memory.stores.in_memory import InMemoryMemoryServiceStore
from services.memory.stores.quality_signals import (
    _attach_dreaming_quality_signals,
    _attach_dreaming_relation_evidence,
    _audit_memory_blocked,
    _audit_memory_executed,
    _context_upsert_allowed_for_working_context,
    _context_upsert_policy_error,
    _context_upsert_policy_metadata,
    _memory_audit_log_blocked,
    _memory_audit_log_executed,
    _memory_traceability,
    _proposal_assurance_blocks_approval,
    _proposal_assurance_digest,
    _proposal_quality_signal,
    _proposal_rejected_retention_expired,
    _proposal_source_ids,
    _proposal_with_validator_assurance,
    _relation_evidence_for_proposal,
    _relation_is_current_and_accepted,
    _relation_metadata_with_defaults,
    _staging_retention_expired,
)
from services.memory.stores.validation import (
    _DockerComposeValidatorBackend,
    _MockValidatorBackend,
    _execute_docker_compose_validator_job,
    _execute_validator_job,
    _prepare_validator_workspace_if_needed,
    _resolve_validator_docker_cli,
    _stage_validator_workspace_if_needed,
    _validator_async_enabled,
    _validator_assurance_evidence,
    _validator_assurance_verdict,
    _validator_execution_backend_name,
    _validator_execution_mode,
    _validator_scope_to_command,
    _validator_subject_from_payload,
    _validator_subject_from_request,
    _validator_worker_root,
)
import os
import shutil

from services.memory.tier_store import (
    ContextStore,
    FactStore,
    GraphStore,
    MemoryLayer,
    RetrievalIndex,
    SessionStore,
)
from services.memory.validator_execution import (
    get_validator_execution_backend,
    register_validator_execution_backend,
)
from services.workspace import persist_validation_report

__all__ = [
    "SessionStore",
    "FactStore",
    "RetrievalIndex",
    "ContextStore",
    "GraphStore",
    "MemoryLayer",
    "os",
    "shutil",
    "register_validator_execution_backend",
    "get_validator_execution_backend",
    "persist_validation_report",
    "MemoryServiceStore",
    "NullMemoryStore",
    "EphemeralMemoryStore",
    "InMemoryMemoryServiceStore",
    "BackedMemoryServiceStore",
    "create_default_memory_service_store",
    "_DockerComposeValidatorBackend",
    "_MockValidatorBackend",
    "_estimate_token_count",
    "_embedding_text_fingerprint",
    "_append_embedding_request_audit",
    "_validator_worker_root",
    "_validator_scope_to_command",
    "_validator_async_enabled",
    "_validator_execution_mode",
    "_validator_execution_backend_name",
    "_resolve_validator_docker_cli",
    "_prepare_validator_workspace_if_needed",
    "_stage_validator_workspace_if_needed",
    "_execute_docker_compose_validator_job",
    "_execute_validator_job",
    "_memory_traceability",
    "_audit_memory_executed",
    "_audit_memory_blocked",
    "_memory_audit_log_executed",
    "_memory_audit_log_blocked",
    "_is_truthy",
    "_context_contains_sensitive_data",
    "_context_scope_present",
    "_compact_summary_text",
    "_build_session_summary_candidate",
    "_proposal_source_ids",
    "_relation_is_current_and_accepted",
    "_relation_evidence_for_proposal",
    "_attach_dreaming_relation_evidence",
    "_proposal_quality_signal",
    "_attach_dreaming_quality_signals",
    "_proposal_assurance_digest",
    "_validator_subject_from_request",
    "_validator_subject_from_payload",
    "_validator_assurance_verdict",
    "_validator_assurance_evidence",
    "_proposal_assurance_blocks_approval",
    "_parse_aware_datetime",
    "_staging_retention_expired",
    "_proposal_rejected_retention_expired",
    "_proposal_with_validator_assurance",
    "_context_upsert_allowed_for_working_context",
    "_context_upsert_policy_error",
    "_context_upsert_policy_metadata",
    "_relation_metadata_with_defaults",
]
